Repository ome/omero-documentation, pull requests merged in 2018-03, with the labels that each got.

#1853 Document removepyramids on upgrade page
  omero/sysadmins/server-upgrade.rst
Labels: develop

#1857 Ignore sourceforge links
  omero/conf.py
Labels: develop

#1856 improve linkchecker for all builds
  common/conf.py
Labels: contributing, develop

#1861 Make homebrew install python2
  omero/sysadmins/unix/server-install-homebrew.rst
  omero/sysadmins/unix/server-installation.rst
Labels: develop

#1860 Django redis
  omero/sysadmins/unix/install-web.rst
  omero/sysadmins/unix/walkthrough/osx/step01_deps_websession.sh
Labels: develop

#1862 app example
  omero/developers/Web/CreateApp.rst
Labels: develop

#1863 Remove Windows support mention & nitpick
  omero/developers/cli/index.rst
  omero/users/cli/index.rst
Labels: develop

#1866 Update auto-generated documentation
  omero/users/history.rst
Labels: develop

#1865 Ignore microsoft link with failing SSL cert
  omero/conf.py
  omero/sysadmins/server-ldap.rst
Labels: develop

#1868 contributing/data-model-schema: Delete obsolete autogen documentation
  contributing/data-model-schema.rst
Labels: contributing
