Repository ome/omero-documentation, pull requests merged in 2018-02, with the labels that each got.

#1843 Rephrase JMX target doc
  omero/sysadmins/server-advanced-configuration.rst
Labels: develop

#1847 Add cleanse bug workaround
  omero/sysadmins/server-backup-and-restore.rst
Labels: develop

#1849 Remove BF breaking jobs
  contributing/ci-bio-formats.rst
  contributing/ci-introduction.rst
  contributing/ci-ome-files.rst
  contributing/schema-changes.rst
Labels: contributing

#1842 debian 9 clarification
  omero/sysadmins/unix/server-debian9-ice36.rst
Labels: develop

#1844 Add sudo example for the java gateway
  omero/developers/Java.rst
Labels: code-needs-merging, develop

#1851 remove mentions of windefault.xml
  omero/developers/logging.rst
  omero/sysadmins/server-security.rst
Labels: develop

#1840 Re-enable Chown all
  omero/sysadmins/whatsnew.rst
  omero/users/cli/chown.rst
Labels: develop

#1841 Update OMERO sidebar for proposed navigation
  common/_templates/globalomerotoc.html
Labels: develop

#1852 Ubuntu clarification
  omero/sysadmins/unix/server-ubuntu-ice36.rst
Labels: develop

#1854 Remove OMERO breaking jobs
  contributing/ci-bio-formats.rst
  contributing/ci-introduction.rst
  contributing/ci-omero.rst
  contributing/schema-changes.rst
Labels: contributing
